#ifndef CONFIG_H
#define CONFIG_H

#define PACKAGE_NAME "supertux2"

#cmakedefine ENABLE_SQDBG

#cmakedefine ENABLE_BINRELOC
#define INSTALL_SUBDIR_BIN "${INSTALL_SUBDIR_BIN}"
#define INSTALL_SUBDIR_SHARE "${INSTALL_SUBDIR_SHARE}"

#define SIZEOF_VOID_P ${CMAKE_SIZEOF_VOID_P}
#if SIZEOF_VOID_P == 8
#define _SQ64
#endif

#cmakedefine HAVE_OPENGL

#cmakedefine HAVE_GLEW

#cmakedefine ENABLE_NPOT_TEXTURES

#define TEXTURE_ALIGNMENT ${TEXTURE_ALIGNMENT}

#cmakedefine ENABLE_LIGHTMAP_FBO

#cmakedefine ENABLE_OPENAL

#cmakedefine ENABLE_SDL_MIXER

#define BUILD_DATA_DIR "${BUILD_DATA_DIR}"

#define BUILD_CONFIG_DATA_DIR "${BUILD_CONFIG_DATA_DIR}"

#cmakedefine ENABLE_TOUCHSCREEN_SUPPORT

#cmakedefine REMOVE_QUIT_BUTTON

#endif /*CONFIG_H*/
